added ctor overload, server can now bind to arbitrary local IP address
eclipse-ecal/fineftp-server pull request #3
Opened 2020-10-27 14:29 UTC by vukovinski

As per #2 

Haven't changed the version. Tested on Windows 10 (19042)

2020-10-28 07:34 UTC, FlorianReimold commented
Great idea! Just 3 remarks:
1. Can you fix the indentation size? I use 2-space indentation and want to keep it consistent
2. In your new constructor, the std::string should be passed as a reference
3. Can you add some documentation to the new functions? 

I will merge the pull request once those points are fixed!

2020-10-28 10:41 UTC, vukovinski commented
Did change the argument.

I did the 2 space formatting, but haven't seen any changes.

Added docs, haven't even seen them in the source code, until you mentioned them 🤣

2020-10-28 15:22 UTC, FlorianReimold requested changes
Some 4 spaces-indentations have survived! ;)

2020-10-28 15:22 UTC, FlorianReimold commented on fineftp-server/src/server_impl.cpp
> +      return acceptor_.local_endpoint().address().to_string();
4 Space Indentation 😉

2020-10-28 15:22 UTC, FlorianReimold commented on fineftp-server/src/server_impl.cpp
> +      }
4 Space Indentation as well 😀

2020-10-28 15:38 UTC, vukovinski commented
done

2020-10-28 15:38 UTC, closed without merging

2020-10-29 08:51 UTC, FlorianReimold commented
Formatting looks good now, but you deleted your repository, so i cannot merge the PR any more.